### ISSUE TITLE
Cannot launch

### ISSUE THREAD

**Issue by VictorLamoine** [jcupitt/rtiacquire#8]
```bash
~/rtiacquire_install/bin$ ./RTIAcquire 
Traceback (most recent call last):
  File "./RTIAcquire", line 10, in <module>
    import rtiacquire.rtiacquire
ImportError: No module named rtiacquire.rtiacquire
```

**Comment by jcupitt** [comment]
Hi, you need to install the program for the wrapper script to work. Try:

```
$ cd GIT/rtiacquire
$ python setup.py install --prefix=/some/install/prefix
```

Without the `--prefix` it'll install to /usr/local/, I think. Then run from anywhere with:

```
$ RTIAcquire
```

You can make a button to launch from the desktop or a menu as well, of course,

**Comment by VictorLamoine** [comment]
I just tested again and it works; my `rtiacquire_install` was already the folder of installation.
Don't know what happened, thanks for the support
