### ISSUE TITLE
Live view does not work on Raspberry Pi

### ISSUE THREAD

**Issue by derosiat2** [jcupitt/rtiacquire#9]
No image appears when the "play button" is pressed. When the "play button" is pressed again to stop the live view stream one image is displayed.

**Comment by jcupitt** [comment]
Does the timeout change fix this? Reopen if it doesn't.

**Comment by derosiat2** [comment]
It fixes it the issue. I just wanted to document it on github to make it easier for some other newbie like me with a Raspberry Pi to find the solution.

**Comment by jcupitt** [comment]
Ah good stuff. Thanks for reporting this!
